package com.idempiere.webservice;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.8.1
//
// Created by Quasar Development at 20/04/2017
//
//---------------------------------------------------


import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.Hashtable;

public class X_ADLoginResponse extends AttributeContainer implements KvmSerializable
{

    
    public String Token;
    
    public Integer status;
    
    public Integer roles;
    
    public String langs;
    
    public Integer orgs;
    
    public Integer clients;
    
    public Integer warehouses;

    public X_ADLoginResponse()
    {
    }

    public X_ADLoginResponse(Object paramObj, X_ExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                Object obj = info.getValue();
                if (info.name.equals("Token"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.Token = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.Token = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("status"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.status = Integer.parseInt(j.toString());
                            }
                        }
                        else if (obj instanceof Integer){
                            this.status = (Integer)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("roles"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.roles = Integer.parseInt(j.toString());
                            }
                        }
                        else if (obj instanceof Integer){
                            this.roles = (Integer)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("langs"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.langs = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.langs = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("orgs"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.orgs = Integer.parseInt(j.toString());
                            }
                        }
                        else if (obj instanceof Integer){
                            this.orgs = (Integer)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("clients"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.clients = Integer.parseInt(j.toString());
                            }
                        }
                        else if (obj instanceof Integer){
                            this.clients = (Integer)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("warehouses"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.warehouses = Integer.parseInt(j.toString());
                            }
                        }
                        else if (obj instanceof Integer){
                            this.warehouses = (Integer)obj;
                        }
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.Token!=null?this.Token:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.status!=null?this.status:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.roles!=null?this.roles:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.langs!=null?this.langs:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.orgs!=null?this.orgs:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.clients!=null?this.clients:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.warehouses!=null?this.warehouses:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 7;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Token";
            info.namespace= "http://idempiere.org/ADInterface/1_0";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "status";
            info.namespace= "http://idempiere.org/ADInterface/1_0";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "roles";
            info.namespace= "http://idempiere.org/ADInterface/1_0";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "langs";
            info.namespace= "http://idempiere.org/ADInterface/1_0";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "orgs";
            info.namespace= "http://idempiere.org/ADInterface/1_0";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "clients";
            info.namespace= "http://idempiere.org/ADInterface/1_0";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "warehouses";
            info.namespace= "http://idempiere.org/ADInterface/1_0";
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    
}

