package com.idempiere.webservice;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.8.1
//
// Created by Quasar Development at 20/04/2017
//
//---------------------------------------------------


import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.Hashtable;

public class X_ADLoginRequest extends AttributeContainer implements KvmSerializable
{

    
    public String user;
    
    public String Token;
    
    public String pass;
    
    public String lang;
    
    public Integer ClientID;
    
    public Integer RoleID;
    
    public Integer OrgID;
    
    public Integer WarehouseID;
    
    public Integer stage;

    public X_ADLoginRequest()
    {
    }

    public X_ADLoginRequest(String user, String token, String pass, String lang, Integer clientID, Integer roleID, Integer orgID,
                            Integer warehouseID, Integer stage){
        this.user = user;
        this.Token = token;
        this.pass = pass;
        this.lang = lang;
        this.ClientID = clientID;
        this.RoleID = roleID;
        this.OrgID = orgID;
        this.WarehouseID = warehouseID;
        this.stage = stage;

    }
    public X_ADLoginRequest(Object paramObj, X_ExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                Object obj = info.getValue();
                if (info.name.equals("user"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.user = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.user = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("Token"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.Token = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.Token = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("pass"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.pass = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.pass = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("lang"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.lang = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.lang = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("ClientID"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.ClientID = Integer.parseInt(j.toString());
                            }
                        }
                        else if (obj instanceof Integer){
                            this.ClientID = (Integer)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("RoleID"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.RoleID = Integer.parseInt(j.toString());
                            }
                        }
                        else if (obj instanceof Integer){
                            this.RoleID = (Integer)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("OrgID"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.OrgID = Integer.parseInt(j.toString());
                            }
                        }
                        else if (obj instanceof Integer){
                            this.OrgID = (Integer)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("WarehouseID"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.WarehouseID = Integer.parseInt(j.toString());
                            }
                        }
                        else if (obj instanceof Integer){
                            this.WarehouseID = (Integer)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("stage"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.stage = Integer.parseInt(j.toString());
                            }
                        }
                        else if (obj instanceof Integer){
                            this.stage = (Integer)obj;
                        }
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return user;
        }
        if(propertyIndex==1)
        {
            return this.Token!=null?this.Token:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.pass!=null?this.pass:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.lang!=null?this.lang:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.ClientID!=null?this.ClientID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.RoleID!=null?this.RoleID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.OrgID!=null?this.OrgID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.WarehouseID!=null?this.WarehouseID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.stage!=null?this.stage:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 9;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "user";
            info.namespace= "http://idempiere.org/ADInterface/1_0";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Token";
            info.namespace= "http://idempiere.org/ADInterface/1_0";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "pass";
            info.namespace= "http://idempiere.org/ADInterface/1_0";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "lang";
            info.namespace= "http://idempiere.org/ADInterface/1_0";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "ClientID";
            info.namespace= "http://idempiere.org/ADInterface/1_0";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "RoleID";
            info.namespace= "http://idempiere.org/ADInterface/1_0";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "OrgID";
            info.namespace= "http://idempiere.org/ADInterface/1_0";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "WarehouseID";
            info.namespace= "http://idempiere.org/ADInterface/1_0";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "stage";
            info.namespace= "http://idempiere.org/ADInterface/1_0";
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    
}

