package com.idempiere.webservice;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.8.1
//
// Created by Quasar Development at 20/04/2017
//
//---------------------------------------------------


import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;

import java.util.Hashtable;

public class X_ModelGetListRequest extends AttributeContainer implements KvmSerializable
{

    
    public X_ModelGetList ModelGetList;
    
    public X_ADLoginRequest ADLoginRequest;

    public X_ModelGetListRequest()
    {
    }

    public X_ModelGetListRequest(Object paramObj, X_ExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                Object obj = info.getValue();
                if (info.name.equals("ModelGetList"))
                {
                    if(obj!=null)
                    {
                        Object j = obj;
                        this.ModelGetList = (X_ModelGetList)__envelope.get(j,X_ModelGetList.class,false);
                    }
                    continue;
                }
                if (info.name.equals("ADLoginRequest"))
                {
                    if(obj!=null)
                    {
                        Object j = obj;
                        this.ADLoginRequest = (X_ADLoginRequest)__envelope.get(j,X_ADLoginRequest.class,false);
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return ModelGetList;
        }
        if(propertyIndex==1)
        {
            return ADLoginRequest;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 2;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = X_ModelGetList.class;
            info.name = "ModelGetList";
            info.namespace= "http://idempiere.org/ADInterface/1_0";
        }
        if(propertyIndex==1)
        {
            info.type = X_ADLoginRequest.class;
            info.name = "ADLoginRequest";
            info.namespace= "http://idempiere.org/ADInterface/1_0";
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    
}

