package com.idempiere.webservice;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.8.1
//
// Created by Quasar Development at 20/04/2017
//
//---------------------------------------------------


import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.Hashtable;

public class X_ModelSetDocAction extends AttributeContainer implements KvmSerializable
{

    
    public String serviceType;
    
    public String tableName;
    
    public Integer recordID=0;
    
    public String recordIDVariable;
    
    public String docAction;

    public X_ModelSetDocAction()
    {
    }

    public X_ModelSetDocAction(Object paramObj, X_ExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                Object obj = info.getValue();
                if (info.name.equals("serviceType"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.serviceType = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.serviceType = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("tableName"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.tableName = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.tableName = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("recordID"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.recordID = Integer.parseInt(j.toString());
                            }
                        }
                        else if (obj instanceof Integer){
                            this.recordID = (Integer)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("recordIDVariable"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.recordIDVariable = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.recordIDVariable = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("docAction"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.docAction = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.docAction = (String)obj;
                        }
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return serviceType;
        }
        if(propertyIndex==1)
        {
            return tableName;
        }
        if(propertyIndex==2)
        {
            return recordID;
        }
        if(propertyIndex==3)
        {
            return this.recordIDVariable!=null?this.recordIDVariable:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return docAction;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 5;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "serviceType";
            info.namespace= "http://idempiere.org/ADInterface/1_0";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "tableName";
            info.namespace= "http://idempiere.org/ADInterface/1_0";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "recordID";
            info.namespace= "http://idempiere.org/ADInterface/1_0";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "recordIDVariable";
            info.namespace= "http://idempiere.org/ADInterface/1_0";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "docAction";
            info.namespace= "http://idempiere.org/ADInterface/1_0";
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    
}

