package com.idempiere.webservice;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.8.1
//
// Created by Quasar Development at 20/04/2017
//
//---------------------------------------------------


import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.Hashtable;

public class X_ModelRunProcess extends AttributeContainer implements KvmSerializable
{

    public Integer AD_Record_ID=0;

    public String getServiceType() {
        return serviceType;
    }

    public void setServiceType(String serviceType) {
        this.serviceType = serviceType;
    }

    public String serviceType;

    public Integer getAD_Record_ID() {
        return AD_Record_ID;
    }

    public void setAD_Record_ID(Integer AD_Record_ID) {
        this.AD_Record_ID = AD_Record_ID;
    }

    public Integer getAD_Process_ID() {
        return AD_Process_ID;
    }

    public void setAD_Process_ID(Integer AD_Process_ID) {
        this.AD_Process_ID = AD_Process_ID;
    }

    public Integer getAD_Menu_ID() {
        return AD_Menu_ID;
    }

    public void setAD_Menu_ID(Integer AD_Menu_ID) {
        this.AD_Menu_ID = AD_Menu_ID;
    }

    public X_DataRow getDataRow() {
        return DataRow;
    }

    public void setDataRow(X_DataRow dataRow) {
        DataRow = dataRow;
    }

    public Integer AD_Process_ID;

    public Integer AD_Menu_ID;

    public X_DataRow DataRow;

    public X_ModelRunProcess()
    {
    }




    public X_ModelRunProcess(Object paramObj, X_ExtendedSoapSerializationEnvelope __envelope) {

        if (paramObj == null)
            return;
        AttributeContainer inObj = (AttributeContainer) paramObj;


        if (inObj instanceof SoapObject) {
            SoapObject soapObject = (SoapObject) inObj;
            int size = soapObject.getPropertyCount();
            for (int i0 = 0; i0 < size; i0++) {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info = soapObject.getPropertyInfo(i0);
                Object obj = info.getValue();
                if (info.name.equals("AD_Process_ID")) {
                    if (obj != null) {

                        if (obj.getClass().equals(SoapPrimitive.class)) {
                            SoapPrimitive j = (SoapPrimitive) obj;
                            if (j.toString() != null) {
                                this.AD_Process_ID = Integer.parseInt(j.toString());
                            }
                        } else if (obj instanceof Integer) {
                            this.AD_Process_ID = (Integer) obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("AD_Record_ID")) {
                    if (obj != null) {

                        if (obj.getClass().equals(SoapPrimitive.class)) {
                            SoapPrimitive j = (SoapPrimitive) obj;
                            if (j.toString() != null) {
                                this.AD_Record_ID = Integer.parseInt(j.toString());
                            }
                        } else if (obj instanceof Integer) {
                            this.AD_Record_ID = (Integer) obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("serviceType")) {
                    if (obj != null) {

                        if (obj.getClass().equals(SoapPrimitive.class)) {
                            SoapPrimitive j = (SoapPrimitive) obj;
                            if (j.toString() != null) {
                                this.serviceType = j.toString();
                            }
                        } else if (obj instanceof String) {
                            this.serviceType = (String) obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("AD_Menu_ID")) {
                    if (obj != null) {

                        if (obj.getClass().equals(SoapPrimitive.class)) {
                            SoapPrimitive j = (SoapPrimitive) obj;
                            if (j.toString() != null) {
                                this.AD_Menu_ID = Integer.parseInt(j.toString());
                            }
                        }
                        else if (obj instanceof Integer) {
                            this.AD_Menu_ID = (Integer) obj;
                        }
                    }
                    continue;
                }
            }
        }
    }



    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return AD_Process_ID;
        }
        if(propertyIndex==1)
        {
            return AD_Record_ID;
        }
        if(propertyIndex==2)
        {
            return AD_Menu_ID;
        }
        if(propertyIndex==3){
            return serviceType;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 4;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "AD_Process_ID";
            info.namespace= "http://idempiere.org/ADInterface/1_0";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "AD_Record_ID";
            info.namespace= "http://idempiere.org/ADInterface/1_0";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "AD_Menu_ID";
            info.namespace= "http://idempiere.org/ADInterface/1_0";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "serviceType";
            info.namespace= "http://idempiere.org/ADInterface/1_0";
        }
    }


    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }


}

