package com.idempiere.webservice;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.8.1
//
// Created by Quasar Development at 20/04/2017
//
//---------------------------------------------------


import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.AttributeInfo;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;

import java.util.Hashtable;

public class X_OutputField extends AttributeContainer implements KvmSerializable
{

    
    public String column;
    
    public String value;
    
    public String Text;

    public X_OutputField()
    {
    }

    public X_OutputField(Object paramObj, X_ExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;







        if (inObj.hasAttribute("column"))
        {	
            Object j = inObj.getAttribute("column");
            if (j != null)
            {
                column = j.toString();
	            
            }
        }

        if (inObj.hasAttribute("value"))
        {	
            Object j = inObj.getAttribute("value");
            if (j != null)
            {
                value = j.toString();
	            
            }
        }

        if (inObj.hasAttribute("Text"))
        {	
            Object j = inObj.getAttribute("Text");
            if (j != null)
            {
                Text = j.toString();
	            
            }
        }

    }

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 0;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
    }
    
    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }



    @Override
    public int getAttributeCount() {
        return 3;
    }
    
    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
        if(index==0)
        {
            info.name = "column";
            info.namespace= "";
            if(this.column!=null)
            {
                info.setValue(this.column);
            }
            
        }
        if(index==1)
        {
            info.name = "value";
            info.namespace= "";
            if(this.value!=null)
            {
                info.setValue(this.value);
            }
            
        }
        if(index==2)
        {
            info.name = "Text";
            info.namespace= "";
            if(this.Text!=null)
            {
                info.setValue(this.Text);
            }
            
        }
    }

    @Override
    public void getAttribute(int i, AttributeInfo attributeInfo) {

    }

    @Override
    public void setAttribute(AttributeInfo attributeInfo) {

    }    
}

