package com.idempiere.webservice;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.8.1
//
// Created by Quasar Development at 20/04/2017
//
//---------------------------------------------------


import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.AttributeInfo;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.ArrayList;
import java.util.Hashtable;

public class X_StandardResponse extends AttributeContainer implements KvmSerializable
{

    
    public String Error;
    
    public ArrayList<X_OutputFields> outputFields =new ArrayList<X_OutputFields>();
    
    public X_RunProcessResponse RunProcessResponse;
    
    public X_WindowTabData WindowTabData;
    
    public X_ADLoginResponse ADLoginResponse;
    
    public Boolean IsError=false;
    
    public Boolean IsRolledBack=false;
    
    public Integer RecordID=0;

    public X_StandardResponse()
    {
    }

    public X_StandardResponse(Object paramObj, X_ExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                Object obj = info.getValue();
                if (info.name.equals("Error"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.Error = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.Error = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("outputFields"))
                {
                    if(obj!=null)
                    {
        
                    
                        if(this.outputFields==null)
                        {
                            this.outputFields = new ArrayList<X_OutputFields>();
                        }
                        Object j =obj;
                        X_OutputFields j1= new X_OutputFields(j,__envelope);
                        this.outputFields.add(j1);
                   
        
                    }
                    continue;
                }
                if (info.name.equals("RunProcessResponse"))
                {
                    if(obj!=null)
                    {
                        Object j = obj;
                        this.RunProcessResponse = (X_RunProcessResponse)__envelope.get(j,X_RunProcessResponse.class,false);
                    }
                    continue;
                }
                if (info.name.equals("WindowTabData"))
                {
                    if(obj!=null)
                    {
                        Object j = obj;
                        this.WindowTabData = (X_WindowTabData)__envelope.get(j,X_WindowTabData.class,false);
                    }
                    continue;
                }
                if (info.name.equals("ADLoginResponse"))
                {
                    if(obj!=null)
                    {
                        Object j = obj;
                        this.ADLoginResponse = (X_ADLoginResponse)__envelope.get(j,X_ADLoginResponse.class,false);
                    }
                    continue;
                }

            }

        }



        if (inObj.hasAttribute("IsError"))
        {	
            Object j = inObj.getAttribute("IsError");
            if (j != null)
            {
                IsError = new Boolean(j.toString());
	            
            }
        }

        if (inObj.hasAttribute("IsRolledBack"))
        {	
            Object j = inObj.getAttribute("IsRolledBack");
            if (j != null)
            {
                IsRolledBack = new Boolean(j.toString());
	            
            }
        }

        if (inObj.hasAttribute("RecordID"))
        {	
            Object j = inObj.getAttribute("RecordID");
            if (j != null)
            {
                RecordID = Integer.parseInt(j.toString());
	            
            }
        }

    }

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.Error!=null?this.Error:SoapPrimitive.NullSkip;
        }
        if(propertyIndex>=1 && propertyIndex < 1+this.outputFields.size())
        {
            return this.outputFields.get(propertyIndex-(1));
        }
        if(propertyIndex==1+this.outputFields.size())
        {
            return this.RunProcessResponse!=null?this.RunProcessResponse:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2+this.outputFields.size())
        {
            return this.WindowTabData!=null?this.WindowTabData:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3+this.outputFields.size())
        {
            return this.ADLoginResponse!=null?this.ADLoginResponse:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 4+outputFields.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Error";
            info.namespace= "http://idempiere.org/ADInterface/1_0";
        }
        if(propertyIndex>=1 && propertyIndex < 1+this.outputFields.size())
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "outputFields";
            info.namespace= "http://idempiere.org/ADInterface/1_0";
        }
        if(propertyIndex==1+this.outputFields.size())
        {
            info.type = X_RunProcessResponse.class;
            info.name = "RunProcessResponse";
            info.namespace= "http://idempiere.org/ADInterface/1_0";
        }
        if(propertyIndex==2+this.outputFields.size())
        {
            info.type = X_WindowTabData.class;
            info.name = "WindowTabData";
            info.namespace= "http://idempiere.org/ADInterface/1_0";
        }
        if(propertyIndex==3+this.outputFields.size())
        {
            info.type = X_ADLoginResponse.class;
            info.name = "ADLoginResponse";
            info.namespace= "http://idempiere.org/ADInterface/1_0";
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }



    @Override
    public int getAttributeCount() {
        return 3;
    }
    
    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
        if(index==0)
        {
            info.name = "IsError";
            info.namespace= "";
            if(this.IsError!=null)
            {
                info.setValue(this.IsError);
            }
            
        }
        if(index==1)
        {
            info.name = "IsRolledBack";
            info.namespace= "";
            if(this.IsRolledBack!=null)
            {
                info.setValue(this.IsRolledBack);
            }
            
        }
        if(index==2)
        {
            info.name = "RecordID";
            info.namespace= "";
            if(this.RecordID!=null)
            {
                info.setValue(this.RecordID);
            }
            
        }
    }

    @Override
    public void getAttribute(int i, AttributeInfo attributeInfo) {

    }

    @Override
    public void setAttribute(AttributeInfo attributeInfo) {

    }    
}

